// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: dchan.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReceiveRequest contains Gob-encoded data to be decoded by the server
// TODO: make it support chunking
type ReceiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data contains the Gob-encoded struct
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_dchan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dchan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_dchan_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiveRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReceiveRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ReceiveResponse acknowledges receipt of the data
// If the server is no longer receiving, the received field will be false.
type ReceiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveResponse) Reset() {
	*x = ReceiveResponse{}
	mi := &file_dchan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResponse) ProtoMessage() {}

func (x *ReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dchan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResponse.ProtoReflect.Descriptor instead.
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return file_dchan_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

// ReceiverRequest is used to register or unregister a receiver for a namespace.
// It contains the namespace, the server ID of the receiver, and the requester.
//
// This is sent to the leader to register or unregister a receiver.
type ReceiverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Requester     string                 `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverRequest) Reset() {
	*x = ReceiverRequest{}
	mi := &file_dchan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverRequest) ProtoMessage() {}

func (x *ReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dchan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverRequest.ProtoReflect.Descriptor instead.
func (*ReceiverRequest) Descriptor() ([]byte, []int) {
	return file_dchan_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiverRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReceiverRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ReceiverRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

// ServerInfo is used to add or remove a voter from the cluster.
//
// We don't need a timeout as we want to block for a reasonable time until the
// operation is complete.
type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAddress     string                 `protobuf:"bytes,1,opt,name=id_address,json=idAddress,proto3" json:"id_address,omitempty"` // The ID and address of the server to add or remove.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_dchan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dchan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_dchan_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfo) GetIdAddress() string {
	if x != nil {
		return x.IdAddress
	}
	return ""
}

var File_dchan_proto protoreflect.FileDescriptor

const file_dchan_proto_rawDesc = "" +
	"\n" +
	"\vdchan.proto\x12\x05dchan\x1a\x1bgoogle/protobuf/empty.proto\"B\n" +
	"\x0eReceiveRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"-\n" +
	"\x0fReceiveResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"j\n" +
	"\x0fReceiverRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\"+\n" +
	"\n" +
	"ServerInfo\x12\x1d\n" +
	"\n" +
	"id_address\x18\x01 \x01(\tR\tidAddress2\xc3\x02\n" +
	"\fDChanService\x128\n" +
	"\aReceive\x12\x15.dchan.ReceiveRequest\x1a\x16.dchan.ReceiveResponse\x12B\n" +
	"\x10RegisterReceiver\x12\x16.dchan.ReceiverRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x12UnregisterReceiver\x12\x16.dchan.ReceiverRequest\x1a\x16.google.protobuf.Empty\x125\n" +
	"\bAddVoter\x12\x11.dchan.ServerInfo\x1a\x16.google.protobuf.Empty\x128\n" +
	"\vRemoveVoter\x12\x11.dchan.ServerInfo\x1a\x16.google.protobuf.EmptyB\x1fZ\x1dgithub.com/m4tth3/dchan/protob\x06proto3"

var (
	file_dchan_proto_rawDescOnce sync.Once
	file_dchan_proto_rawDescData []byte
)

func file_dchan_proto_rawDescGZIP() []byte {
	file_dchan_proto_rawDescOnce.Do(func() {
		file_dchan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dchan_proto_rawDesc), len(file_dchan_proto_rawDesc)))
	})
	return file_dchan_proto_rawDescData
}

var file_dchan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dchan_proto_goTypes = []any{
	(*ReceiveRequest)(nil),  // 0: dchan.ReceiveRequest
	(*ReceiveResponse)(nil), // 1: dchan.ReceiveResponse
	(*ReceiverRequest)(nil), // 2: dchan.ReceiverRequest
	(*ServerInfo)(nil),      // 3: dchan.ServerInfo
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_dchan_proto_depIdxs = []int32{
	0, // 0: dchan.DChanService.Receive:input_type -> dchan.ReceiveRequest
	2, // 1: dchan.DChanService.RegisterReceiver:input_type -> dchan.ReceiverRequest
	2, // 2: dchan.DChanService.UnregisterReceiver:input_type -> dchan.ReceiverRequest
	3, // 3: dchan.DChanService.AddVoter:input_type -> dchan.ServerInfo
	3, // 4: dchan.DChanService.RemoveVoter:input_type -> dchan.ServerInfo
	1, // 5: dchan.DChanService.Receive:output_type -> dchan.ReceiveResponse
	4, // 6: dchan.DChanService.RegisterReceiver:output_type -> google.protobuf.Empty
	4, // 7: dchan.DChanService.UnregisterReceiver:output_type -> google.protobuf.Empty
	4, // 8: dchan.DChanService.AddVoter:output_type -> google.protobuf.Empty
	4, // 9: dchan.DChanService.RemoveVoter:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dchan_proto_init() }
func file_dchan_proto_init() {
	if File_dchan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dchan_proto_rawDesc), len(file_dchan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dchan_proto_goTypes,
		DependencyIndexes: file_dchan_proto_depIdxs,
		MessageInfos:      file_dchan_proto_msgTypes,
	}.Build()
	File_dchan_proto = out.File
	file_dchan_proto_goTypes = nil
	file_dchan_proto_depIdxs = nil
}
