// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: dchan.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DChanService_Receive_FullMethodName            = "/dchan.DChanService/Receive"
	DChanService_RegisterReceiver_FullMethodName   = "/dchan.DChanService/RegisterReceiver"
	DChanService_UnregisterReceiver_FullMethodName = "/dchan.DChanService/UnregisterReceiver"
	DChanService_AddVoter_FullMethodName           = "/dchan.DChanService/AddVoter"
	DChanService_RemoveVoter_FullMethodName        = "/dchan.DChanService/RemoveVoter"
)

// DChanServiceClient is the client API for DChanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DChanService provides RPC methods for distributed channel operations
type DChanServiceClient interface {
	// Receive accepts Gob-encoded data for the server to decode
	Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (*ReceiveResponse, error)
	RegisterReceiver(ctx context.Context, in *ReceiverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnregisterReceiver(ctx context.Context, in *ReceiverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddVoter(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveVoter(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dChanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDChanServiceClient(cc grpc.ClientConnInterface) DChanServiceClient {
	return &dChanServiceClient{cc}
}

func (c *dChanServiceClient) Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (*ReceiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveResponse)
	err := c.cc.Invoke(ctx, DChanService_Receive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dChanServiceClient) RegisterReceiver(ctx context.Context, in *ReceiverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DChanService_RegisterReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dChanServiceClient) UnregisterReceiver(ctx context.Context, in *ReceiverRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DChanService_UnregisterReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dChanServiceClient) AddVoter(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DChanService_AddVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dChanServiceClient) RemoveVoter(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DChanService_RemoveVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DChanServiceServer is the server API for DChanService service.
// All implementations must embed UnimplementedDChanServiceServer
// for forward compatibility.
//
// DChanService provides RPC methods for distributed channel operations
type DChanServiceServer interface {
	// Receive accepts Gob-encoded data for the server to decode
	Receive(context.Context, *ReceiveRequest) (*ReceiveResponse, error)
	RegisterReceiver(context.Context, *ReceiverRequest) (*emptypb.Empty, error)
	UnregisterReceiver(context.Context, *ReceiverRequest) (*emptypb.Empty, error)
	AddVoter(context.Context, *ServerInfo) (*emptypb.Empty, error)
	RemoveVoter(context.Context, *ServerInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedDChanServiceServer()
}

// UnimplementedDChanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDChanServiceServer struct{}

func (UnimplementedDChanServiceServer) Receive(context.Context, *ReceiveRequest) (*ReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedDChanServiceServer) RegisterReceiver(context.Context, *ReceiverRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterReceiver not implemented")
}
func (UnimplementedDChanServiceServer) UnregisterReceiver(context.Context, *ReceiverRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterReceiver not implemented")
}
func (UnimplementedDChanServiceServer) AddVoter(context.Context, *ServerInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVoter not implemented")
}
func (UnimplementedDChanServiceServer) RemoveVoter(context.Context, *ServerInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVoter not implemented")
}
func (UnimplementedDChanServiceServer) mustEmbedUnimplementedDChanServiceServer() {}
func (UnimplementedDChanServiceServer) testEmbeddedByValue()                      {}

// UnsafeDChanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DChanServiceServer will
// result in compilation errors.
type UnsafeDChanServiceServer interface {
	mustEmbedUnimplementedDChanServiceServer()
}

func RegisterDChanServiceServer(s grpc.ServiceRegistrar, srv DChanServiceServer) {
	// If the following call pancis, it indicates UnimplementedDChanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DChanService_ServiceDesc, srv)
}

func _DChanService_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DChanServiceServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DChanService_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DChanServiceServer).Receive(ctx, req.(*ReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DChanService_RegisterReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DChanServiceServer).RegisterReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DChanService_RegisterReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DChanServiceServer).RegisterReceiver(ctx, req.(*ReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DChanService_UnregisterReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DChanServiceServer).UnregisterReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DChanService_UnregisterReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DChanServiceServer).UnregisterReceiver(ctx, req.(*ReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DChanService_AddVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DChanServiceServer).AddVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DChanService_AddVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DChanServiceServer).AddVoter(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DChanService_RemoveVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DChanServiceServer).RemoveVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DChanService_RemoveVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DChanServiceServer).RemoveVoter(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// DChanService_ServiceDesc is the grpc.ServiceDesc for DChanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DChanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dchan.DChanService",
	HandlerType: (*DChanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _DChanService_Receive_Handler,
		},
		{
			MethodName: "RegisterReceiver",
			Handler:    _DChanService_RegisterReceiver_Handler,
		},
		{
			MethodName: "UnregisterReceiver",
			Handler:    _DChanService_UnregisterReceiver_Handler,
		},
		{
			MethodName: "AddVoter",
			Handler:    _DChanService_AddVoter_Handler,
		},
		{
			MethodName: "RemoveVoter",
			Handler:    _DChanService_RemoveVoter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dchan.proto",
}
